declaration = struct_decl;
            | func_decl ;
            | var_decl ;

param = ident ":" type ;
params = param "," params ;
           | param ;
func_decl = "func" ident "(" params ")" block ;

var_decl = "let" ident ":" type ["=" expr] ";" ;

field = ident ":" type;
fields = field { "," field } [ "," ] ;
struct_decl = "struct" ident "{" fields "}" ;

enum_mod = "noprefix" ;
enum_mods = enum_mod "," enum_mods ;
          | enum_mod ;
variants = variant { "," variants } [ "," ] ;
enum_decl = "enum" ident [ enum_mods ] "{" variants "}" ;
